
#
# File: build.yml | Note: Following file maintains the Build Pipeline for the Project 
#

#
# MIT License
# 
# Copyright (c) 2025 ShaidK
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: Build Snowball Project
on:
    pull_request:
        types: [ opened, synchronize ]
    push:
        branches:
        - build
jobs:
  build:
    name: Build
    uses: shaidk/snowball_test/.github/workflows/ci.yml@84c93e21528aa0de0ea4f38e5092421e497069c1
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: lint
        run: |
          echo "Executing Linting"
          sleep 10
  lint_toml: 
    name: Lint TOML
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: toml
        run: |
          echo "Executing TOML Linting"
          sleep 10
  lint_yaml: 
    name: Lint YAML
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: yaml
        run: |
          echo "Executing YAML Linting"
          sleep 10
  test:
    name: Successful Test Project
    runs-on: ubuntu-latest
    needs: [ lint_toml, lint_yaml ]
    steps:
      - name: success_test
        run: |
          echo "Executing Success Unit Tests"
          sleep 10
  success_test:
    name: Successful Test
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: success_test
        run: |
          echo "Executing Success Unit Tests"
          sleep 10
  failure_test:
    name: Failure Test Project
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: failure_test
        run: |
          echo "Executing Failure Unit Tests"
          sleep 10
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [ success_test, failure_test ]
    steps:
      - name: coverage
        run: |
          echo "Executing Failure Unit Tests"
          sleep 10
    
        
