name: Publish Docker
on:
  push:
    branches: [ "build" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    name: Publish Docker
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Snowball Project Repository
        uses: actions/checkout@v6

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest"
          
