name: Publish Docker
on:
  push:
    branches: [ "build" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    name: Publish Docker
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Snowball Project Repository
        uses: actions/checkout@v6

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Integrate Docker Tags Naming
        run: | 
          echo "ACTOR=${GITHUB_ACTOR,,}" >> $GITHUB_ENV 
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Echo
        run: |
          echo "$ACTOR"
          echo "$REPOSITORY"
          echo "$REGISTRY"

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v6.18.0
        with:
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.REPOSITORY }}:latest
          
